<?php
	$this->add_asset_extension("flot",array( 
        "jquery.flot.min.js", 
        "jquery.flot.resize.min.js", 
        "jquery.flot.pie.min.js", 
        "jquery.flot.stack.min.js", 
        "jquery.flot.crosshair.min.js", 
        "jquery.flot.categories.min.js", 
        "jquery.flot.time.min.js",
        "\$__\$.js" 
    ),false); 
?>